---

- name: install packages
  package: name={{item}} state=latest
  with_items:
     - nginx

- service:
   name: nginx
   state: started
   enabled: yes

- name: nginx app
  register: nginx_update
  copy:
     src: "/vagrant/roles/webserver/files/nginx.conf"
     dest: "/etc/nginx/conf.d/hello.conf"
     group: root
     mode: "744"
     force: yes

- name: remove default config
  when: nginx_update.changed
  file:
     path: /etc/nginx/sites-available/default
     state: absent

- name: reload nginx
  when: nginx_update.changed
  service:
     name: nginx
     state: reloaded

